### PR TITLE
Adding mute option.

### PR DESCRIPTION
**Pull request by maliMirkec**
@rizqirizqi Would you mind adding the mute option, please?

### CODE REVIEW

**Comment by rizqirizqi** [comment]
Hi @maliMirkec, thanks for the PR!

It looks like you're updating the snapshot file manually. You can run `yarn test -u` to update the snapshot file.

And, can you remove the webp files in sample-images/ directory? I already added it to the gitignore on master.

**Comment by maliMirkec** [comment]
@rizqirizqi Updated!

**Comment by maliMirkec** [comment]
@rizqirizqi Thanks for merging. Would you publish a new version soon?

**Comment by rizqirizqi** [comment]
@maliMirkec [v2.2.0](https://github.com/rizqirizqi/webpconvert/releases/tag/v2.2.0) released :rocket:

**Pull request merged**
